language: php

notifications:
  on_success: never
  on_failure: change

php:
  - 5.3
  - 5.5

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
    - php: 5.3
      env: WP_VERSION=latest WP_MULTISITE=1

before_script:
  - composer install --no-interaction
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
   - if [[ ${TRAVIS_PHP_VERSION:0:3} != "5.2" ]]; then vendor/bin/phpmd classes text cleancode,codesize,naming,unusedcode; fi
   - if [[ ${TRAVIS_PHP_VERSION:0:3} != "5.2" ]]; then vendor/bin/phpcpd -n classes; fi
   - vendor/bin/phpcs -n --report=emacs --standard=phpcs.ruleset.xml classes
   - phpunit
